language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
# command to install dependencies
install:
  - pip install codecov
  - ./installOrgToAnki.sh
# command to run tests
script:
  - python3 setup.py nosetests
